### PR TITLE
Fix configuration file upload

### PR DESCRIPTION
**Pull request by esune**
Reverts a change introduced in #150 to `allow.py` that caused the schema file upload to not work.

Dependency updates as needed.

### CODE REVIEW

**Comment by Gavinok** [comment]
Fixes #157

**Comment by Gavinok** [comment]
@esune any reason to rename `cred_schema` to `schema`?

**Review by Gavinok — APPROVED** [review]
Looks good but what is the purpose of the renamed field?

**Comment by esune** [comment]
@Gavinok I had renamed it to `cred_schema` to correct a pydantic warning about shadowing a base class variable. This seems to have caused file uploads for schemas to break - unsure why - so I am reverted the change to get everything back to a working state and will deal with the error separately.

**Review by ianco — APPROVED** [review]

**Pull request merged**
